### ISSUE TITLE
init.lua:96: 'for' limit must be a number

### ISSUE THREAD

**Issue by Ale32bit** [SquidDev/artist#13]
This happened randomly while idling.

Cannot replicate

Full stacktrace:
```
init:96: 'for' limit must be a number
stack traceback:
  peripherals.lua:83: in function <peripherals.lua:62>
  [C]: in function 'xpcall' context.lua:72: in function <context.lua:71>
```

**Comment by SquidDev** [comment]
For reference:

https://github.com/SquidDev-CC/artist/blob/5385f8ac6894d29b82d82109df46f60e835f0a19/artist/items/init.lua#L96

This implies that a peripheral was detached just before it was rescanned. It may be worth adding some fallback (`... or 0`, remove the peripheral, etc...) here to prevent against any issues.
