### ISSUE TITLE
Furnace: Slow Extracting & Inserting

### ISSUE THREAD

**Issue by jhagrid77** [SquidDev/artist#14]
Problem/Bug: When having a large number of furnaces connected, artist has complications extracting the output and inserting fuel from/into them.

What should happen: Smooth/fast (or at least not slow) extraction and insertion.

How to replicate: Stack 4 modems ontop of each other. Add 4 furnaces on 3 out of 4 sides of the modems. Repeat 2x. Insert items to be smelted and observe.

I'm quite curious why extracting is as slow as it is. I wonder if it's to prevent server lag, or just artist not being designed to be a smelting program (which I understand). I do hope this bug report was useful however and if any additional information is needed, please ask.

**Comment by SquidDev** [comment]
Plethora by default rescans _one_ furnace every 10 seconds. The rationale here is that furnaces are jolly slow to smelt, so you don't need to be polling them super regularly - I normally dump a stack into each of them and then walk away, so the additional latency isn't really an issue.

This limit can be changed by opening the `.artist` file and looking for `furnace_rescan` - you can probably knock this down to 1. While the limit is nominally set there to reduce server load (I try to minimise the amount of polling I do), it's probably a little too high.

I'll also have a look into rewriting the furnace polling system - there's some definite improvements I could do with scanning furnaces currently cooking more regularly.
