### ISSUE TITLE
[BUG] Whole system fails to pick-up/drop-off/read items when using chests directly connected to computer

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [SquidDev/artist#19]
Heya, while setting up Artist for a friend, i set up the network and then the computer that they'd use for the interface. I set up pick-up and drop-off points on the left and right of the computer, but then there was errors popping up in the log (attached here: [log.txt](https://github.com/SquidDev-CC/artist/files/8333435/log.txt)), but connecting the chests with modems do work

**Comment by SquidDev** [comment]
Chests not connected via a modem are never going to work, but I guess we should exclude them from being indexed and error when invalid configuration is given.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Ah that's fair
