### ISSUE TITLE
[bug] Enabling TrashCan with existing amounts of item, requires prompting to trash them

### ISSUE THREAD

**Issue by Merith-TK** [SquidDev/artist#22]
![image](https://user-images.githubusercontent.com/10422110/175785235-c84ec386-6a99-4fb4-a984-a058e0b5abc8.png)
this number wont go down until it is updated (IE: putting ONE item in the system)
and then it will only go down an certain amount

511
![image](https://user-images.githubusercontent.com/10422110/175785265-36400aaf-c446-4ec4-96ae-ebf578b707e2.png)

511
![image](https://user-images.githubusercontent.com/10422110/175785289-1af2fc1f-74fa-4b5f-8e39-9cf17c19eba3.png)

It appears to only get rid of 511 at an time when I prompt it, 

(note, my item cap for this is 2560)

**Comment by SquidDev** [comment]
Probably need to start another scan (if needed) once we've found the trashcan

https://github.com/SquidDev-CC/artist/blob/bbb5cf56e9e4ebfa44da5b9e559f45379a07190e/src/artist/items/trashcan.lua#L31
