### ISSUE TITLE
[Bug] Block IDs(?) are displayed instead of item names

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [SquidDev/artist#23]
![image](https://user-images.githubusercontent.com/88039945/179071853-501ce786-d8f7-4e2d-9a63-9489b93d751b.png)
I'm running CC: Restitched on 1.19, if you wanna know the modpack, it is here: https://modrinth.com/modpack/uqm

**Comment by SquidDev** [comment]
Odd, that suggests metadata isn't picked up at all. Would you be able to upload your `.artist.d/log` file?

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
> Odd, that suggests metadata isn't picked up at all. Would you be able to upload your `.artist.d/log` file?

Sure, i'll do it rn

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
https://pastebin.com/UZPAfCK1

**Comment by SquidDev** [comment]
Very odd, there's nothing obvious in the logs. You could try deleting the cache (`rm .artist.d/cache`) and see if that helps at all.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
> Very odd, there's nothing obvious in the logs. You could try deleting the cache (`rm .artist.d/cache`) and see if that helps at all.

just did that now, still didn't work rip

**Comment by Ocawesome101** [comment]
this looks like a CC:R issue.  those are the keys present in the `.lang` file that Minecraft uses, so i'd guess CC:R is failing to find those keys in whatever language you have configured.

**Comment by SquidDev** [comment]
Ahh, Fabric just doesn't load modded language files, hence them not showing up. I thought CC:R had a mixin which fixed that - odd.

**Comment by Ocawesome101** [comment]
all of these are vanilla items.

**Comment by SquidDev** [comment]
Oh lol, so they are.
