### ISSUE TITLE
Config file keeps resetting

### ISSUE THREAD

**Issue by Pawelnougoed** [SquidDev/artist#25]
For some reason, artist keeps resetting my config file. It has been quite irritating when wanting to set up drop off chests

**Comment by SquidDev** [comment]
What do you mean by resetting? Does it remove commented out bits of code (which is expected) or entirely revert to the original version. 

The latter should only happen when there's syntax errors in the code, though we probably shouldn't do that.

**Comment by Pawelnougoed** [comment]
It resets it completely. I don't think I'm making a syntax error, though I
will check and get back to you.

**Comment by Pawelnougoed** [comment]
Nevermind. Apperently I am more stupid that I thought I was.
Thank you for helping out

**Comment by nodlek-ctrl** [comment]
Would you mind sharing what you did? I'm having a word of trouble working out how to alter the config, and cant get modules going either
