### ISSUE TITLE
[QUESTION] Custom Modules

### ISSUE THREAD

**Issue by hzFishy** [SquidDev/artist#26]
Hello, I would like to know how I can write and implement customs modules.
I am currently working on a porject and I need to have another turtle give or take items

**Comment by SquidDev** [comment]
So in order to add a custom module (this includes the [display example](https://github.com/SquidDev-CC/artist/blob/vnext/examples/display.lua)), you need to do the following:

 1. Add the file to `.artist.d/src/` (so for instance, save the example file to `.artist.d/src/display.lua`
 2. Open `.artist.d/src/launch.lua` and require your module. There should be a commented out example there already, but you want to have something like:

    ```lua
    local context = require "artist"()
    context:require "display" -- Or whatever you've named your file.
    context.config:save()
    context:run()
    ```

As far as what the actual module should look like, that's harder to know without knowing more details. Have a read through the linked example above, that should explain the basis at least.

**Comment by hzFishy** [comment]
Thank you very much !

May I ask another question here ? Or you prefer that I open a new issue ?

**Comment by SquidDev** [comment]
If it's just a question, probably easiest to chuck it on here.

**Comment by hzFishy** [comment]
I would like to know where do you store the `count` of each items/blocs in the storage 
I was able to retreive what items/blocs where IN the storage with the `cache` file, but I wasn't able to find how to get the `count` of the items/blocs stored

I hope its possible to do that

**Comment by SquidDev** [comment]
Item counts aren't ever persisted to disk, we rescan chests on each startup. All item data (including counts) is stored in the [the `Items` class](https://github.com/SquidDev-CC/artist/blob/vnext/src/artist/core/items.lua) - see the `item_cache` field.

You definitely shouldn't be poking the cache file - that's not guaranteed to be up-to-date.

**Comment by hzFishy** [comment]
Hello again,
Thank you very much for your answers, it helped me a lot :)

I was working on how to get the count from you Items class, but the complexity of you code (it is complex for me, I am new to coding with class on Lua) makes it hard for me to know how to get the exact amount of each item stored.

So I wanted to ask you this question, I know its seems not right but I prefer doing this then spending 10h+ finding on how to do that. Because I still have other stuff to do afterwards and I don't want to finish next month.

Since it is your code, and you know how it works, could you write for me a cutom module (or anything else that could do the trick) that:
> _returns args_, the `name `(e.g: `minecraft:<>`) of the block and its `count`
or
> _writes in a file_ in a table (like in your cache file) the `name `(e.g: `minecraft:<>`) of the block and its `count`
(e.g:
```
{name="minecraft:grass_block",count=954}
```
_JSON format would be the best_)

If you are interested, please add me on Discord `Fishy#0021` so we can discuss more in private, and of course I will pay you for this (we can talk about your price and "deadline" in dms)

If before deciding anything you would like to know why I want all of this, please ask me here or in my Discord dms.

Cheers!

**Comment by SquidDev** [comment]
```lua
return function(context)
  local items = context:require "artist.core.items"

  local function save_as_json()
    -- Build up a list of items.
    local out = {}
    for hash, item in pairs(items.item_cache) do
      table.insert(out, {name = hash, count = item.count})
    end

    -- Convert to JSON
    local json = textutils.serializeJSON(out)

    -- Write to a file.
    local file = fs.open("dump.json", "w")
    file.write(json)
    file.close()
  end

  -- Save the file every change. This is a little inefficient - you 
  -- might want to debounce it like we do in the example module.
  context.mediator:subscribe("items.change", function()
    save_as_json()
  end)
end
```

**Comment by hzFishy** [comment]
Thank you so much <3
It is working perfectly

**Comment by hzFishy** [comment]
**Hello :)**
I write in this closed issue because I have one more little question and I don't want to open a new issue.
Thanks to you, my project is *almost* finished, but I face one more problem, and its has the same main issue than the other request i did for the count.

Lets imagine that in the `/src/` folder of `.artist.d` I have a file called `extract_stuff.lua`, in this file I have "variables" containing the `id` of a item (that exist in the storage) and the `count` of this item requested.

(1) Lets say that I already checked that this `item` EXIST and its COUNT is __equal or lower__ than how much there is in the storage.

How could I link this `extract_stuff.lua` script with your extraction system ? So I can "request a extraction" of any item with its count like if a player was using the turtle interface ?.
I hope that with the (1) statement it is "easy" and possible to do it.

Me and my friend working on the project will be very grateful to you if you could do this for us 🙏
If you have any questions please ask then
