### ISSUE TITLE
Pocket computer support

### ISSUE THREAD

**Issue by hzFishy** [SquidDev/artist#30]
Before starting anything regarding creating a extension making possible to a user to use the same interface of the turtle on a pocket computer, I would like to know if there is any specific limitations or other stuff i should know regarding how artist works

**Comment by SquidDev** [comment]
It should be possible - the UI is intentionally decoupled from the inventory management. You will run into #17 here, in that while Artist has been designed to be used over a network, there's not actually any support for it yet.

**Comment by hzFishy** [comment]
Ok thanks for the answers!
